name: Build & Publish

on:
  # On release events (also when a published release is converted from/to prerelease), push all patterns
  release:
    types: [released, prereleased]

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build and push bee-api image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY }}/i-am-bee/bee-api:latest
            ${{ vars.DOCKER_REGISTRY }}/i-am-bee/bee-api:${{ steps.get_version.outputs.VERSION }}
          cache-from: type=registry,ref=${{ vars.DOCKER_REGISTRY }}/i-am-bee/bee-api:buildcache
          cache-to: type=registry,ref=${{ vars.DOCKER_REGISTRY }}/i-am-bee/bee-api:buildcache,mode=max
  worker-python:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Free disk space
        id: free_disk_space
        shell: bash
        # Based on https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
        # and https://github.com/jlumbroso/free-disk-space
        run: |
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /usr/local/.ghcup || true
          sudo rm -rf "/usr/local/share/boost" || true
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true

      - name: Build and push bee-api-workers-python image with Docling extraction backend
        uses: docker/build-push-action@v6
        with:
          file: ./workers/python/Dockerfile.docling
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY }}/i-am-bee/bee-api-workers-python:latest-docling
            ${{ vars.DOCKER_REGISTRY }}/i-am-bee/bee-api-workers-python:${{ steps.get_version.outputs.VERSION }}-docling
          cache-from: type=registry,ref=${{ vars.DOCKER_REGISTRY }}/i-am-bee/bee-api-workers-python:buildcache-docling
          cache-to: type=registry,ref=${{ vars.DOCKER_REGISTRY }}/i-am-bee/bee-api-workers-python:buildcache-docling,mode=max
