name: build and publish release image to Quay

on:
  release:
    types: [released, prereleased]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build and push bee-api image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            quay.io/${{ env.IMAGE_NAME }}:latest
            quay.io/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
          cache-from: type=registry,ref=quay.io/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=$quay.io/${{ env.IMAGE_NAME }}:buildcache,mode=max
